spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mentorship_dev
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      data-locations: classpath:db/dev-data.sql
