spring:
  application:
    name: mentorship

logging:
  file:
    name: logs/mentorship.json
  structured:
    format:
      file: ecs
    ecs:
      service:
        environment: development
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB