spring:
  cache:
    type: redis
    cache-names:
      - users
      - usersById
      - tasks
      - tasksById
    redis:
      time-to-live: 10m
      cache-null-values: false
  profiles:
    default: dev
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false
    web:
      pageable:
        max-page-size: 100
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
