spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mentorship_dev
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      data-locations: classpath:db/dev-data.sql

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus
  metrics:
    tags:
      application: mentorship
    distribution:
      percentiles-histogram:
        http.server.requests: true
