input {
    file {
      path => ["/var/log/mentorship/mentorship.json"]
      mode => "tail"
      start_position => "beginning"
      sincedb_path => "/usr/share/logstash/data/mentorship.sincedb"
      codec => json
      ecs_compatibility => "v8"
    }
  }

  output {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      ecs_compatibility => "v8"
      data_stream => "true"
      data_stream_type => "logs"
      data_stream_dataset => "mentorship"
      data_stream_namespace => "development"
    }
  }